name: Publish LaTeX Templates
on: [push]
jobs:
  Publish-Templates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out template repo
        uses: actions/checkout@v3
      - name: Create file
        run: |
          echo "Hallo Welt" > ./hallo
          ls ${{ github.workspace }}
          cat ./hallo
          cat ./README.md
      - name: Check public repo
        uses: actions/checkout@v3
        with:
          repository: feberts/latex-dest
      - name: Run ls
        run: |
          ls ${{ github.workspace }}
