name: Publish LaTeX Templates
on: [push]
jobs:
  Publish-Templates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo (templates)
        uses: actions/checkout@v3
        with:
          path: templates
      - name: Check out remote repo (website)
        uses: actions/checkout@v3
        with:
          repository: feberts/latex-dest
          path: website
      - name: Write and push
        run: |
          echo Hallo
          cd ${{ github.workspace }}/website
          cat README.md
          cd ${{ github.workspace }}/templates
          cat README.md
