name: Publish LaTeX Templates
on: [push]
jobs:
  Publish-Templates:
    runs-on: ubuntu-latest
    env:
      NEW_WEBSITE: "${{ github.workspace }}/new_website/"
    steps:
      - name: Check out this repo (templates)
        uses: actions/checkout@v3
        with:
          path: templates
      - name: Check out remote repo (website)
        uses: actions/checkout@v3
        with:
          repository: feberts/latex-dest
          path: website
      - name: Generate website from templates
        run: |
          mkdir "$NEW_WEBSITE"
          ls -l
          cd ${{ github.workspace }}/templates
          ./generate-website.sh "$NEW_WEBSITE"
      - name: Add website to remote repo
        run: |
          cd ${{ github.workspace }}/website
          git rm -r .
          cp -r "$NEW_WEBSITE"/* .
          git add .
      - name: Set up SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
      - name: Commit and push to remote repo
        run: |
          cd ${{ github.workspace }}/website
          git remote set-url origin git@github.com:feberts/latex-dest.git
          git config user.name "github action"
          git config user.email "noreply"
          git commit -am "update"
          git push
