name: Publish LaTeX Templates
on: [push]
jobs:
  Publish-Templates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out template repo
        uses: actions/checkout@v3
      - name: Create file
        run: |
          echo "Hallo Welt" > ./hallo
          ls ${{ github.workspace }}
          cat ./hallo
          cat ./README.md
      - name: Check public repo
        uses: actions/checkout@v3
        with:
          repository: feberts/latex-dest
          path: pub_repo
      - name: Write and push
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_PUBLIC_REPO }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          cd ${{ github.workspace }}/pub_repo
          git remote set-url origin git@github.com:feberts/latex-dest.git
          git config user.name "Peter"
          git config user.email "noreply"
          echo "123" >> ./README.md
          cat ./README.md
          git commit -am "update"
          git push